name: Release to github packages

on:
  release:
    types: [created]

jobs:
  call-workflow-maven-deploy:
    uses: felleslosninger/github-workflows/.github/workflows/ci-build-publish-lib.yml@main
    permissions:
      contents: read
      packages: write
    with:
    # disabled due to rate-limiting
      trivy-library-disable-scan: true
      java-version: 21
      package-version: ${{ github.event.release.tag_name }}
      deployment-repository: ${{ github.repository }}
    secrets: inherit
