name: Release to github packages

on:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Deploy to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${GITHUB_ACTOR}</username><password>\${env.GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          REPO="github::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
          mvn versions:set -B -DnewVersion="${{ github.event.release.tag_name }}"
          mvn -B deploy -DaltDeploymentRepository="${REPO}"
